
services:
  web:
    environment:
      - UVICORN_RELOAD=1
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=devsecret
    volumes:
      - ./:/app
      - ./data:/data
      - ./static:/app/static
      - ./app/templates:/app/templates
